### ISSUE TITLE
CFLAGS and CPPFLAGS are not propagated

### ISSUE THREAD

**Issue by olebole** [Caltech-IPAC/Montage#12]
The standard `CFLAGS` are not propagated in the Makefile, but overwritten in every subdirectory. This has a few disadvantages: First, a local change (like the include dir for wcstools, which is `/usr/include/wcstools` on Debian) has to be set on each fo the zillion subdirs, and it is impossible to set compilation options from the environment. The latter is used in Debian to provide different build options (like with or without debugging), and to enable [specific hardening flags](https://wiki.debian.org/HardeningWalkthrough) and warnings/errors (`-fstack-protector-strong -Wformat -Werror=format-security `).

Also, the standard `CPPFLAGS` and `LDFLAGS` are not recognized. They are also used for hardening in Debian (`-D_FORTIFY_SOURCE=2`).

Would it be possible to recognize `CFLAGS`, `CPPFLAGS`, and `LDFLAGS` from the build environment?

**Comment by JohnGood** [comment]
While we have maintained a presence for Montage on GitHub for a several years now,
until recently the actual source code control and issue tracking were done through
other, institution-specific, tools.  So while we addressed all issues in a timely
manner, we were regrettably lax about cleaning up these issues in GitHub.

We haven't addressed this issue yet but we agree it is a good idea and will leave
the issue open.

**Comment by JohnGood** [comment]
I've reviewed this in some detail and there is only one area where we would have a problem.  For some libraries we have to use our copy rather than relying on one you have installed.  The one you mention is a good example:  We have added projections to the WCS library that are not in the standard release yet so if we use your copy some of our functionality will break.

We only use a few third-party libraries and we include copies precisely to avoid having to worry about the local environment getting ahead (or behind) where we are.  So while we would be OK with passing the the bulk of the contents of CFLAGS and LDFLAGS set by you, we are not comfortable when it comes to library-related stuff.  If you know a good way of using CFLAGS but overriding parts of it, I'm open to suggestion.

**Comment by olebole** [comment]
In Debian, we always favour the libraries that are provided with the system over those that come with a package. If there are extensions, I usually contact the author of the third-party software to discuss the inclusion of this extension. Optimally here would be a direct contact between the two package upstream authors, as these changes are often useful for other users of the third-party library as well.
In the case of wcstools, this happened, and the patches (of your last release) are included in the new release of wcstools. As I am the package manager of many third-party packages, another option would be to include these changes in their Debian packages.

This means that in any case I will make big efforts to get software run properly with the third-party software as dependencies instead of included copies, and I would therefore patch out an "overriding" here anyway. I think this is up to the package maintainer (or user, who installs a package) what they prefer to use, even when this results in a build that is not supported by upstream (on bug reports, I check this before forwarding).

**Comment by JohnGood** [comment]
I just checked the current release of wcstools and neither of the projections I added (HPX for HEALPix/HiPS) and TOA for WWT) are in there yet (we added them in 2016).  I just finished a large set of tools for making HiPS maps and I could not have afforded to wait four+ years and counting for the official update.

Upon reflection, it looks to me like your use case could be handled by us changing our Makefiles to use "CFLAGS += ...", etc.  If that would work with the way your system works, we are willing to try it out.  We can work this out off-line.

**Comment by olebole** [comment]
`CFLAGS+=` is fine for me, thanks.
wrt. upstream changes: this probably took quite long, since after your implementation and your release, I needed to package it, noticed the change and forwarded it to Jessica Mink then. Shortcutting this by a direct discussion would probably improve the turnaround time here.

**Comment by JohnGood** [comment]
Thanks, will do.

We notified Jessica of our intent on 5/31/2017 and you mentioned it to 
her as already released on 4/10/17
so it has been in the works for at least four years.

My point is that we cannot be sure to stay synched with the current 
state of libraries, either because
we have the unusual situation like this of being "ahead" or because we 
have not tested the newer version
(e.g. CFITSIO).

Right now, if you link to the official WCS library, you won't be able to 
use any of the new HEALPix/HiPS
tools we are about to release (actually are already available in our 
"develop" branch on GitHub).

**Comment by olebole** [comment]
We are currently about to release Debian 11 "Bullseye" and are in a freeze; so the next montage version would go into Debian only after that. I will have a discussion with Jessica about her plans, and I could patch wcstools locally as well.

**Comment by JohnGood** [comment]
That would be great.
