### ISSUE TITLE
Change in behavior of mBestImage

### ISSUE THREAD

**Issue by astrofrog** [Caltech-IPAC/Montage#21]
In Montage 3.3, the following command returned a result:

```
$ mBestImage m31_2mass_k.tbl 10.6847929 41.269065
[struct stat="OK", file="2mass-atlas-971024n-k0080033.fits", url="http://irsa.ipac.caltech.edu/ibe/data/twomass/full/full/971024n/s008/image/ki0080033.fits.gz", edgedist=0.046368]
```

The input table can be found here:

https://gist.githubusercontent.com/astrofrog/0ae04bf0ba80cc4bbdc9f617e52b7369/raw/8a4f8b6e97c1f916c40d89677cd23b60c0e1ab85/m31_2mass_k.tbl

However, in Montage 4.0 and 5.0, no results are returned:

```
[struct stat="ERROR", msg="No image covers this point"]
```

Is this expected? If so, why?

**Comment by JohnGood** [comment]
While we have maintained a presence for Montage on GitHub for a several years now,
until recently the actual source code control and issue tracking were done through
other, institution-specific, tools.  So while we addressed all issues in a timely
manner, we were regrettably lax about cleaning up these issues in GitHub.

There was a sign error in an angle calculation.  It has been fixed in the GitHub 
"develop" branch.
