### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by Henrietta1989** [Caltech-IPAC/Montage#41]
I have Montage 4.0 in my Mac installed using Cakebrew and Cakebrew says "Conflicts: wdiff (because Both install an mdiff executable)"

Home:~ Henrietta$ montage -title "Movie Name\nSubtitle" -geometry +4+4 /Volumes/Backup/Pics/capture*.png /Volumes/Backup/Pics/output.png
-bash: montage: command not found

I don't know a thing about unix so i don't know how to fix that. Thanks

**Comment by JohnGood** [comment]
Our manager was supposed to respond to this but if he did so it apparently wasn't through GitHub.  I'm afraid you are referring to a different package than ours so the issue is moot.  We do have an "mDiff" executable (the case is different but Macs can have trouble with that) but is shouldn't be installing into system directories anyway (and could just be renamed if it was).
