### ISSUE TITLE
altin.hdr not created in mProjExec when using mTANHdr; possible bug was located.

### ISSUE THREAD

**Issue by izff** [Caltech-IPAC/Montage#44]
I am running mProjExec on some images, and none of the images were processed.

On checking the debug log, I noticed these messages:

>Image 0:
>Input wcs ptype: [ZPN]
>mGetHdr(4_w20050921_01513_st.fit) -> [ncard=95]
>mTANHdr() -> [fwdxerr=0.00793472, fwdyerr=0.0086687, fwditer=18, revxerr=0.0139163, revyerr=0.0122212, reviter=51]
>Using distorted TAN on input: max error = 0.0139163
>mProjectPP(4_w20050921_01513_st.fit) -> [File altin.hdr not found.] (COMPUTED/INTRINSIC)
 >inp2p = COMPUTED
>outp2p = INTRINSIC

So, altin.hdr cannot be found. I went on to check the generation process of this file in the source code. 

In Monage/mProjExec.c, I found code snip:
`

        sprintf(cmd, "mTANHdr %s/%s %s/%s",
            projdir, origstr, projdir, altinstr);
         

         if(debug)
         {
            printf("[%s]\n", cmd);
            fflush(stdout);
         }

         svc_run(cmd);

`

I thought this one was correct, but it was not used to compile and build the binary mProjExec.
I went on and found this file, MontageLib/ProjExec/montageProjExec.c .
In this file, I thought the equivalent code block was:

`

         tanHdr = mTANHdr(origHdr, altout, 5, 50, 0.01, 0, 0);

         if(mProjExec_debug)
         {
            fprintf(mProjExec_fdebug, "mTANHdr() -> [%s]\n", tanHdr->msg);
            fflush(mProjExec_fdebug);
         }

`
tanHdr = mTANHdr(origHdr, **altout**, 5, 50, 0.01, 0, 0);
The hdr generated from the original hdr was written to altout rather than altin!

I think this is why my image projection failed. Can someone help me to verify this?

**Comment by JohnGood** [comment]
You are correct and it will be fixed in the next release of the code.

**Comment by katosei** [comment]
Similarly to the problem izff had, I also have a problem in re-projecting fits files. After executing the command 
'_mProjExec -p imagedir images.tbl template.hdr resultdir stats.tbl_',
this results in the following std output;
'_[struct stat="OK", module="mProjExec", count=2, failed=2, nooverlap=0]_'
It is clear that something wrong has occured. Actually only altout.hdr  and orig.hdr has been generated under the resultdir directory, and I cannot see any reprojected fits file. Also in stat.tbl, only I can see the message '_File resultdir_I1/altin.hdr not found_.'
I downloaded what I need to install Montage from [GitHub](https://github.com/Caltech-IPAC/Montage) from which [the official Montage page](http://montage.ipac.caltech.edu/docs/download2.html) recommends to download files, but the problem seems to keep existing. Are there any files to further download to fix this problem?
I would be happy if anyone kindly reply to me.
